apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring-stack

resources:
  - namespace.yaml
  - source.yaml
  - release.yaml

labels:
  - pairs:
      orise.io/tenant: common
      orise.io/environment: dev