apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres-edge

labels:
  - pairs:
      app.kubernetes.io/name: postgres
      app.kubernetes.io/instance: edge-db
      app.kubernetes.io/component: database
      app.kubernetes.io/part-of: orise-infra
      orise.io/deployment-model: edge

resources:
  - namespace.yaml
  - secret.yaml
  - service.yaml
  - statefulset.yaml
