apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik

resources:
  - base/repository.yaml
  # Default to private-cloud or use overlays in actual usage
  - private-cloud/release.yaml
