apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx-flux-example

# Add version label to all resources
labels:
  - pairs:
      app.kubernetes.io/version: "v0.0.3"

resources:
  - deployment.yaml
  - service.yaml
