apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-nginx

# Add version annotation to all resources
commonAnnotations:
  app.kubernetes.io/version: "v0.0.2"

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
