apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - source.yaml
  - influxdb-release.yaml
  - chronograf-release.yaml
  - fluentbit-release.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: monitoring-stack

