apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openobserve
resources:
  # For testing we keep the namespace manually, on production the repo is only one not for branch.
  #- namespace.yaml
  - secret.yaml
  - source.yaml
  - release.yaml
