apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ../../base

configMapGenerator:
  - name: influxdb-values
    files:
      - values.yaml=values-influxdb.yaml
  - name: chronograf-values
    files:
      - values.yaml=values-chronograf.yaml
  - name: fluentbit-values
    files:
      - values.yaml=values-fluentbit.yaml

generatorOptions:
  disableNameSuffixHash: true

labels:
  - pairs:
      orise.io/environment: private-cloud
      orise.io/criticality: high
