apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres-flux-example

resources:
  - repository.yaml
  - operator.yaml
  - private-cloud/cluster.yaml
  - edge/cluster.yaml
